name: Container
on: push
jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:14-buster
    steps:
      - name: log node version
        run: node -v
      - name: step with docker
        uses: docker://node:14.11.0-alpine3.10 # statt einer github action rufen wir direkt ein docker image auf
        with: # mit with 端bergeben wir die Werte in die Aktion bzw in unserem Fall in den Container
          entrypoint: /bin/echo # Pfad zum ausf端hrbaren file - type -a node
          args: Hello world
      - name: log node version
        uses: docker://node:14.11.0-alpine3.10 # statt einer github action rufen wir direkt ein docker image auf
        with: # mit with 端bergeben wir die Werte in die Aktion bzw in unserem Fall in den Container
          entrypoint: /usr/local/bin/node # Pfad zum ausf端hrbaren file - type -a node
          args: -v
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username": "hello", "address": "dwded"}'''
      - name: Get users
        run: "curl -X GET http://localhost:3001/api/users"
