name: Container
on: push
jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:14.11.0-alpine3.12
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release