name: Matrix
on: push
jobs:
  node-versions:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 8, 10]
      # fail-fast: true
      # max-parallel: 2 # wir können die jobs limitieren
    runs-on: ${{ matrix.os }}
    steps:
      - name: log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: log node version
        run: node -v